(function(a,e){var f=e.X2={};f.shareLink=function(c){function b(){if(e.clipboardData){var a=c.find("label").html()+"\n\r"+d.val();e.clipboardData.setData("Text",a);alert("\u5df2\u7ecf\u6210\u529f\u590d\u5236\u4ee5\u4e0b\u5185\u5bb9\u5230\u526a\u8d34\u677f\uff0c\u4f60\u53ef\u4ee5\u901a\u8fc7Ctrl+V\u7c98\u8d34\u5230QQ/MSN/\u8bba\u575b\u7b7e\u540d\u6863\uff1a\n--------\n"+a)}else c.find("input[type=text]")[0].select(),alert("\u60a8\u4f7f\u7528\u7684\u6d4f\u89c8\u5668\u4e0d\u652f\u6301\u6b64\u590d\u5236\u529f\u80fd\uff0c\u8bf7\u4f7f\u7528Ctrl+C\u6216\u9f20\u6807\u53f3\u952e\u3002")}c=a(c).parent();var d=c.find("input[type=text]");d.val().match(/^http:\/\/t\.cn\/(.*?)/)?b():a.getJSON("//api.weibo.com/short_url/shorten.json?url_long="+encodeURIComponent(d.val())+"&source=3564068769&callback=?",
function(a){a[0]&&a[0].url_short&&d.val(a[0].url_short);b()})};f.ping=function(a){(new Image).src=a};f.openYY=function(a){var b="";try{new ActiveXObject("yy_checker.Checker.1"),b="yy://join:room_id="+a}catch(d){b="//yy.duowan.com/go.html#"+a}e.open(b);return!1};f.search=function(c){google.load("search","1",{language:"zh-CN",nocss:!0});google.setOnLoadCallback(function(){var b=new google.search.CustomSearchControl("004737766081905067025:yabscsqa4cc");b.setResultSetSize(google.search.Search.FILTERED_CSE_RESULTSET);
var d=new google.search.DrawOptions;b.draw("cse",d);b.setSearchCompleteCallback(null,function(){var c=e.location.host;a.each(a(".gs-result"),function(){var b=a(this).find(".gs-visibleUrl-short").html();b&&b!==c&&a(this).html(a(this).html().replace(RegExp(b,"ig"),c))})});b.execute(c)},!0)};var j=e.location.host=="localhost";f=[];var h=[],k=[];f.push(function(){e.onerror=function(){return!0}});f.push(function(){document.execCommand("BackgroundImageCache",!1,!0)});h.push(function(){var c=a("#q").attr("disabled",
!1);a.trim(c.val())||c.val("\u8bf7\u8f93\u5165\u7535\u89c6\u5267\u540d");a("#search").submit(function(){var b=a.trim(c.val());if(b.length<1||b=="\u8bf7\u8f93\u5165\u7535\u89c6\u5267\u540d")return c.focus(),alert("\u8bf7\u8f93\u5165\u7535\u89c6\u5267\u540d"),!1;e.location=root+"search/?"+encodeURIComponent(b)+".html";return!1});c.focus(function(){c.val()=="\u8bf7\u8f93\u5165\u7535\u89c6\u5267\u540d"&&c.val("");c.css("color","#000")}).blur(function(){c.val()||(c.val("\u8bf7\u8f93\u5165\u7535\u89c6\u5267\u540d"),c.css("color","#D8D8D8"))})});h.push(function(){function c(){f.hide();g.attr("class","open");i.slideDown("fast");e.__playlistshow__=!0}function b(){i.slideUp("slow",
function(){g.attr("class","close");f.show()});e.__playlistshow__=!1}function d(){i.css({top:g.offset().top+g.height(),left:g.offset().left-i.outerWidth()+g.width()})}var g=a("#pl-ctrl-btn");if(g.length){var i=a("#playlist"),f=a("#next"),h=a("#playlist iframe");h.length||(h=a('<iframe frameborder="0" src="" tabindex="-1"></iframe>').css({opacity:0,display:"block",position:"absolute","z-index":-1,height:i.height(),width:i.width()}).insertBefore(i.find("ul")));g.click(function(a){e.__playlistshow__?
b():c();a.stopPropagation()});i.click(function(a){a.stopPropagation()});a(document).click(b);d();a(e).load(d).resize(d);e.location.hash=="#pl"&&c()}});h.push(function(){var c=a(".idx");if(c.length){var b=a(".link-list li"),d=[];a("a",c).click(function(){a(this).blur()});a("a.enable",c).click(function(){var g=a(this),e=g.html(),f=a("a.on",c).removeClass("on");e=="\u5168\u90e8"?f.length&&b.show():((f.length?d[f.html()]:b).css({display:"none"}),d[e]||(d[e]=a(".link-list li:has(a[rel="+e+"])")),g.addClass("on"),
d[e].css({display:""}))}).mouseover(function(){var c=a(this).html();d[c]||(d[c]=a(".link-list li:has(a[rel="+c+"])"))})}});f.push(function(){if(!j)e.lainframe=function(){},function(a){var b=1,d=1;try{var g=document.cookie+"",f=g.match(/(^| )AJSTAT_ok_pages=([^;]*)(;|$)/);b=f?parseInt(unescape(f[2]),10)+1:1;var h=(new Date(+new Date+36E5)).toGMTString();document.cookie="AJSTAT_ok_pages="+b+";path=/;expires="+h;d=(f=g.match(/(^| )AJSTAT_ok_times=([^;]*)(;|$)/))?parseInt(unescape(f[2]),10)+(b==1?1:0):
1;document.cookie="AJSTAT_ok_times="+d+";path=/;expires="+h}catch(j){}g=document.referrer;try{g=e.parent.document.referrer}catch(k){}try{g=e.top.document.referrer}catch(m){}a={svid:7,id:a,tcolor:screen.pixelDepth||screen.colorDepth,sSize:screen.width+","+screen.height,tzone:-(new Date).getTimezoneOffset()/60,itpages:b,ttimes:d,referrer:escape(g),vpage:escape(e.location.href)};b=[];for(var l in a)b.push(l+"="+a[l]);(new Image).src="//web2.51.la:82/go.asp?"+b.join("&")}(2347960)});h.push(function(){e.weatherHandler=
function(c){c=c.split(";");a("#weather-text").html(c[0]+"&nbsp;"+c[1]+"~"+c[2]);a("#weather-icon").attr("src",c[3]);if(a.browser.msie)a("#weather-icon")[0].outerHTML="<span style=\"width:16px; height:16px;line-height:16px;display:inline-block;filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+c[3]+"', sizingMethod='scale');\"></span>";a("#weather-button").show()};a.getScript("//www.soso.com/tb.q?fn=weatherHandler",function(){function c(){d.css({top:b.offset().top+b.height(),left:b.offset().left-
262+b.width()})}var b=a("#weather-button"),d=a('<div id="weather-board">\u8bf7\u7a0d\u5019...</div>').insertAfter(a("#weather-button")).mouseout(function(){a(this).hide()});b.length&&(b.mouseover(function(){a("iframe",d).length||d.html('<iframe class="weather-more-iframe" src="//www.soso.com/tb.q?cid=webq.wea" frameborder="0" scrolling="no"></iframe>');d.show()}),a(document).click(function(){d.hide()}),c(),a(e).resize(c))})});h.push(function(){a(".close-icon").click(function(){a(this).parent().hide()})});a.each(f,
function(a,b){try{b()}catch(d){}});a(document).ready(function(){a.each(h,function(a,b){try{b()}catch(d){}})});a(e).load(function(){a.each(k,function(a,b){try{b()}catch(d){}})})})(jQuery,window);
